import React, { useEffect, useState } from "react";
import api, { formatApiError } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Progress } from "@/components/ui/progress";
import { Badge } from "@/components/ui/badge";
import { Sparkles, Map as MapIcon } from "lucide-react";
import { toast } from "sonner";

const PHASES = [
  { key: "phase_30", label: "First 30 days" },
  { key: "phase_60", label: "Days 31-60" },
  { key: "phase_90", label: "Days 61-90" },
];

export default function Roadmap() {
  const [roadmap, setRoadmap] = useState(null);
  const [busy, setBusy] = useState(false);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    (async () => {
      try {
        const { data } = await api.get("/roadmap");
        setRoadmap(data.roadmap);
      } finally { setLoading(false); }
    })();
  }, []);

  const generate = async () => {
    setBusy(true);
    try {
      const { data } = await api.post("/roadmap/generate");
      setRoadmap(data.roadmap);
      toast.success("Roadmap generated");
    } catch (e) {
      toast.error(formatApiError(e));
    } finally { setBusy(false); }
  };

  const toggle = async (phase, taskId, done) => {
    // optimistic
    const next = JSON.parse(JSON.stringify(roadmap));
    const t = next[phase]?.tasks?.find((x) => x.id === taskId);
    if (t) t.done = done;
    setRoadmap(next);
    try {
      await api.post("/roadmap/toggle", { phase, task_id: taskId, done });
    } catch (e) {
      toast.error(formatApiError(e));
    }
  };

  if (loading) return <div className="text-muted-foreground">Loading...</div>;

  return (
    <div className="space-y-8" data-testid="roadmap-page">
      <header className="flex items-start justify-between flex-wrap gap-4">
        <div>
          <div className="text-xs font-bold uppercase tracking-[0.2em] text-muted-foreground">30/60/90 roadmap</div>
          <h1 className="mt-2 text-3xl md:text-4xl font-heading font-black tracking-tighter">Your personal study plan</h1>
          <p className="mt-2 text-muted-foreground">Generated by AI using your profile, projects and goals.</p>
        </div>
        <Button onClick={generate} disabled={busy} className="rounded-full font-semibold gap-2" data-testid="roadmap-generate-btn">
          <Sparkles className="w-4 h-4" /> {busy ? "Generating..." : roadmap ? "Regenerate" : "Generate roadmap"}
        </Button>
      </header>

      {!roadmap && (
        <Card className="p-12 text-center" data-testid="roadmap-empty">
          <MapIcon className="w-12 h-12 mx-auto text-muted-foreground opacity-50" />
          <div className="mt-4 font-heading font-bold text-xl">No roadmap yet</div>
          <div className="text-muted-foreground mt-1">Make sure your profile is filled, then click "Generate roadmap" above.</div>
        </Card>
      )}

      {roadmap && (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {PHASES.map((p) => {
            const phase = roadmap[p.key];
            if (!phase) return null;
            const total = phase.tasks?.length || 0;
            const done = phase.tasks?.filter((t) => t.done).length || 0;
            const pct = total ? Math.round((done / total) * 100) : 0;
            return (
              <Card key={p.key} className="p-6 flex flex-col" data-testid={`roadmap-${p.key}`}>
                <div className="text-xs uppercase tracking-[0.2em] text-muted-foreground">{p.label}</div>
                <h3 className="mt-2 font-heading font-bold text-xl">{phase.title}</h3>
                <div className="mt-3 flex items-center gap-3 text-sm">
                  <Progress value={pct} className="flex-1 h-2" />
                  <span className="font-mono font-bold tabular-nums">{done}/{total}</span>
                </div>
                <div className="mt-4 space-y-2 flex-1">
                  {phase.tasks?.map((t) => (
                    <label key={t.id} className="flex items-start gap-3 p-2 rounded-md hover:bg-secondary cursor-pointer transition-colors" data-testid={`task-${p.key}-${t.id}`}>
                      <Checkbox checked={!!t.done} onCheckedChange={(v) => toggle(p.key, t.id, !!v)} className="mt-0.5" data-testid={`task-checkbox-${t.id}`} />
                      <div className="flex-1">
                        <div className={`text-sm ${t.done ? "line-through text-muted-foreground" : ""}`}>{t.title}</div>
                        {t.category && <Badge variant="secondary" className="mt-1 text-[10px]">{t.category}</Badge>}
                      </div>
                    </label>
                  ))}
                </div>
              </Card>
            );
          })}
        </div>
      )}
    </div>
  );
}
